- name: Setup Infra Server
  import_playbook: 00-setup-infra-server.yaml

- name: Setup OCP Web
  import_playbook: 01-setup-ocp-web.yaml

- name: Setup OCP Bootstrap
  import_playbook: 02-setup-ocp-bootstrap.yaml

- name: Setup OCP Master Nodes
  import_playbook: 03-setup-ocp-master.yaml

- name: Setup OCP Worker Nodes
  import_playbook: 04-setup-ocp-worker.yaml

- name: Configure OCP Load Balancer and Final Checks
  import_playbook: 05-setup-ocp-load-balancer.yaml

- name: Restore UDF SSH Key
  import_playbook: 06-restore-ssh-keys.yaml

- name: Setup Linux Jumphost
  import_playbook: 07-setup-jumphost.yaml

- name: Debug messages
  hosts: ocp_web
  remote_user: root
  vars:
    remotefile: '/usr/share/nginx/html/installations/auth/kubeadmin-password'
  tasks:
    - name: Read password
      ansible.builtin.slurp:
        src: '{{ remotefile }}'
      register: slurpfile
    - name: Print OCP Console credentials
      debug:
        msg:
          - 'You can access to OCP Console throught Jumphost (Credentials: user/user)'
          - 'URL: https://console-openshift-console.apps.ocp.f5-udf.com/'
          - 'Username: kubeadmin'
          - "Password: {{ slurpfile['content'] | b64decode }}"
